### ISSUE TITLE
Considerations for Caching Poetry in GHA

### ISSUE THREAD

**Issue by Hasenpfote** [Hasenpfote/pyenv_poetry_tox_pytest_example#2]

**Comment by Hasenpfote** [comment]
Draft - 1 ... 動作確認済

## YAML

```yaml
name: Draft - 1

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8']
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Make cache paths
        id: make-cache-paths
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            PATH1='~\AppData\Local\pypoetry'
            PATH2='~\AppData\Roaming\pypoetry'
            PATH3='~\AppData\Roaming\Python\Scripts'
            echo 'CACHE_PATHS<<EOF' >> $GITHUB_ENV
            echo -e "${PATH1}\n${PATH2}\n${PATH3}" >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
          else
            PATH='~/.local'
            echo "CACHE_PATHS=${PATH}" >> $GITHUB_ENV
          fi

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CACHE_PATHS }}
          key: lab3-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Linux/macOS
        if: runner.os != 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: bash
        env:
          POETRY_HOME: ~/.local
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # https://github.com/python-poetry/poetry/issues/6875#issuecomment-1315476316
      - name: Install Poetry for Windows
        if: runner.os == 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -

      - name: Add paths for macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Add paths for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Add-Content $env:GITHUB_PATH "$env:APPDATA\pypoetry\venv\Scripts"

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: lab3-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev

      - name: Install project
        run: poetry install --no-interaction --only-root

      - name: Get the environment name for Tox
        id: vars
        shell: python
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              value = str(${{ matrix.python-version }}).replace('.', '')
              print(f'env=py{value}', file=fh)

      - name: Test with pytest
        run: |
          #poetry run tox -e py # This is not possible on Windows.
          poetry run tox -e ${{ steps.vars.outputs.env }}
```

## 備忘録

### for Linux
基本的には何もしなくてもキャッシュ機構が利用可能.  

### for maxOS
パスを通しておく必要がある.
```yaml
      - name: Add paths for macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH  
```

### for Windows
`POETRY_HOME` を利用すると挙動が怪しくなる.  
ここでは `Poetry` のデフォルト動作に任せた.  
パスを通しておく必要があるが, インストール時のパスはキャッシュ利用時には使えない.  
共通で使えるように次のように設定をする.  
```yaml
      - name: Add paths for Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Add-Content $env:GITHUB_PATH "$env:APPDATA\pypoetry\venv\Scripts"
```

### その他
Linux / macOS は `bash` で良いとして, Windoiws は中途半端なので止めたほうがよさそう.  
yaml 下部の `Tox` 内では  `allowlist_externals = poetry` で上位の `poetry` を利用しようとするが,  
`bash` では環境変数に格納されるパスが POSIX-style になり `Tox` が認識しなくなる.

**Comment by Hasenpfote** [comment]
Windows で `POETRY_HOME` を指定すると色々と失敗する例.

- `POETRY_HOME: ~\.local` にするとキャッシュの復元時にシンボリックリンクの作成で失敗
- `POETRY_HOME: ~\local` も同様
- `POETRY_HOME: C:\Users\runneradmin\.local` も同様

![2022-12-23 19 25 01 github com 8b50be486b02](https://user-images.githubusercontent.com/1502467/209319760-de8b466e-7c20-49f4-815e-9c616f5d6d09.png)

**Comment by Hasenpfote** [comment]
Draft - 2

`Poetry` (1.3.1) で正常に動作することを確認済み.  

## 機能
- Linux / macOS / Windows で `Poetry` をキャッシュし再利用可能
- `Poetry` が生成する仮想環境をキャッシュし再利用可能

## YAML

## 備忘録

## その他

**Comment by Hasenpfote** [comment]
## Poetry のローカルキャッシュ

### for Linux
`POETRY_HOME: ~/.local`
![2022-12-24 14 33 43 github com d1888d26e857](https://user-images.githubusercontent.com/1502467/209423036-ce31912e-1b9a-4faa-b47a-cf9f95e70f30.png)

### for macOS
`POETRY_HOME: ~/.local`
![2022-12-24 14 34 12 github com 581b5acecb1a](https://user-images.githubusercontent.com/1502467/209423038-17671c17-3263-4051-a704-3f55c64bb22e.png)

### for Windows
`POETRY_HOME:`
![2022-12-24 14 28 21 github com 988e3ccf88d3](https://user-images.githubusercontent.com/1502467/209423041-35f0fccd-4b0a-4236-831a-99093debfc9e.png)

**Comment by Hasenpfote** [comment]
Draft - 3

`Poetry` (1.3.1) で正常に動作することを確認済み.  

`Draft - 2` をベースに各 OS で `Poetry` のデフォルトインストール.  

## 機能
- Linux / macOS / Windows で `Poetry` をキャッシュし再利用可能
- `Poetry` が生成する仮想環境をキャッシュし再利用可能
- 各種設定を matrix に移行
- `Poetry` の[デフォルトインストール](https://python-poetry.org/docs/#installation).  

## YAML
```yaml
name: Draft - 3

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.7', '3.8']
        include:
          - os: ubuntu-20.04
            poetry_home: ''
            poetry_path: ${HOME}/.local/share/pypoetry/venv/bin
            poetry_cache_paths: |
              ~/.local/share/pypoetry
          - os: macos-latest
            poetry_home: ''
            poetry_path: ${HOME}/Library/Application Support/pypoetry/venv/bin
            poetry_cache_paths: |
              ~/Library/Application Support/pypoetry
          - os: windows-latest
            poetry_home: ''
            poetry_path: ${APPDATA}\pypoetry\venv\Scripts
            poetry_cache_paths: |
              ~\AppData\Roaming\pypoetry
              ~\AppData\Roaming\Python\Scripts
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ${{ matrix.poetry_cache_paths }}
          key: lab6-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Linux/macOS
        if: runner.os != 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: bash
        env:
          POETRY_HOME: ${{ matrix.poetry_home }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Poetry for Windows
        if: runner.os == 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: pwsh
        env:
          POETRY_HOME: ${{ matrix.poetry_home }}
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -

      - name: Add Poetry to the PATH environment variable
        if: matrix.poetry_path != ''
        shell: bash
        run: |
          echo "${{ matrix.poetry_path }}" >> $GITHUB_PATH

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: lab6-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev

      - name: Install project
        run: poetry install --no-interaction --only-root

      - name: Get the environment name for Tox
        id: vars
        shell: python
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              value = ''.join(str(${{ matrix.python-version }}).split('.', 2)[0:2])
              print(f'env=py{value}', file=fh)

      - name: Test with pytest
        run: |
          #poetry run tox -e py # This is not possible on Windows.
          poetry run tox -e ${{ steps.vars.outputs.env }}
```

## 備忘録

## その他

**Comment by Hasenpfote** [comment]
## Windows 時のシンボリックリンク復元問題

[`Draft - 3`](https://github.com/Hasenpfote/pyenv_poetry_tox_pytest_example/issues/2#issuecomment-1364500258) をベースに `POETRY_HOME: ~\.local` で再考.  

### シンボリックリンク復元に失敗する例
```yaml
          - os: windows-latest
            poetry_home: ~\.local
            poetry_path: ${USERPROFILE}\.local\venv\Scripts
            poetry_cache_paths: |
              ~\.local\VERSION
              ~\.local\bin\poetry.exe
              ~\.local\venv
```
![2022-12-24 21 45 30 github com 5749897d5113](https://user-images.githubusercontent.com/1502467/209436768-8bee0e34-a44c-473d-bf70-1a4fd93337c6.png)

### シンボリックリンクの復元を回避する例
```yaml
          - os: windows-latest
            poetry_home: ~\.local
            poetry_path: ${USERPROFILE}\.local\venv\Scripts
            poetry_cache_paths: |
              ~\.local\VERSION
              #~\.local\bin\poetry.exe
              ~\.local\venv
```
![2022-12-24 21 47 57 github com 7f05b532490d](https://user-images.githubusercontent.com/1502467/209436856-6e53b51f-a108-42e8-9836-393d259cab9d.png)

**Comment by Hasenpfote** [comment]
Draft - 4

正常に動作することを確認済み.  
[`Draft - 3`](https://github.com/Hasenpfote/pyenv_poetry_tox_pytest_example/issues/2#issuecomment-1364500258) をベースに `Tox` 実行コマンドを修正.  

## 機能
- Linux / macOS / Windows で `Poetry` をキャッシュし再利用可能
- `Poetry` が生成する仮想環境をキャッシュし再利用可能
- 各種設定を matrix に移行
- `Poetry` のデフォルトインストールに準拠  

## YAML

```yaml
name: Poetry caching feature

on: workflow_dispatch

permissions:
  contents: read

jobs:
  create-cache:
    name: caching 1/2 - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.7', ]
        include:
          - os: ubuntu-20.04
            poetry_home: ''
            poetry_path: ''
            poetry_cache_paths: |
              ~/.local/share/pypoetry
              ~/.local/bin/poetry
          - os: macos-latest
            poetry_home: ''
            poetry_path: ${HOME}/.local/bin
            poetry_cache_paths: |
              ~/Library/Application Support/pypoetry
              ~/.local/bin/poetry
          - os: windows-latest
            poetry_home: ''
            poetry_path: ${APPDATA}\pypoetry\venv\Scripts
            poetry_cache_paths: |
              ~\AppData\Roaming\pypoetry
              ~\AppData\Roaming\Python\Scripts\poetry.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ${{ matrix.poetry_cache_paths }}
          key: temp-poetry-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Linux/macOS
        if: runner.os != 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: bash
        env:
          POETRY_HOME: ${{ matrix.poetry_home }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Install Poetry for Windows
        if: runner.os == 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: pwsh
        env:
          POETRY_HOME: ${{ matrix.poetry_home }}
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
      - name: Add Poetry to the PATH environment variable
        if: matrix.poetry_path != ''
        shell: bash
        run: |
          echo "${{ matrix.poetry_path }}" >> $GITHUB_PATH
  
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: temp-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root --with dev

      - name: Install project
        run: poetry install --no-interaction --only-root

      - name: Test with pytest
        shell: bash
        run: |
          if [ $RUNNER_OS == 'Windows' ]; then
            # Avoid referencing the wrong Python version.
            VER='${{ matrix.python-version }}'
            ARR=(${VER//./ })
            poetry run tox -e "py${ARR[0]}${ARR[1]}"
          else
            poetry run tox -e py
          fi
```

**Comment by Hasenpfote** [comment]
## Windows の `poetry run tox - e py` で意図しないバージョンを参照する
[Managing environments](https://python-poetry.org/docs/managing-environments/) によると
> By default, Poetry will try to use the Python version used during Poetry’s installation to create the virtual environment for the current project.

なので Linux では正常な動作となっている.  
![2022-12-28 12 07 14 github com 83841a496a82](https://user-images.githubusercontent.com/1502467/209751061-1f76870a-a07c-421e-b449-680dcc2babc9.png)
![2022-12-28 12 07 32 github com 247a5cded4d8](https://user-images.githubusercontent.com/1502467/209751069-f719c97f-ca80-4d11-bc45-4b8c0702fd88.png)




sys=3.9.13, venv=3.7.9, py=3.11.1

![2022-12-26 18 23 13 github com c276fba827ea](https://user-images.githubusercontent.com/1502467/209531750-165b00f6-9221-4d16-83ce-86f261e808c0.png)
![2022-12-26 18 23 40 github com 5e7792979eb3](https://user-images.githubusercontent.com/1502467/209531758-048fff2b-ab80-40b0-9b5c-4ea1c4c592a9.png)
![2022-12-26 18 24 11 github com 5f9b3c79bd9c](https://user-images.githubusercontent.com/1502467/209531768-1b892773-ff38-4e2f-ac16-6cf2c5ebe5c0.png)
![2022-12-26 18 24 23 github com c906669e6229](https://user-images.githubusercontent.com/1502467/209531777-298282e0-e195-495e-b0ba-3439c315fb00.png)
3.11.1 は何処から来ているのか？

[2022/12/28] `poetry use env` で環境を指定していないことが原因.  
[Managing environments](https://python-poetry.org/docs/managing-environments/) によると
> By default, Poetry will try to use the Python version used during Poetry’s installation to create the virtual environment for the current project.

とあるが, Windows だけは例外で 
![2022-12-28 11 52 14 github com 0406515f0e16](https://user-images.githubusercontent.com/1502467/209749789-3230edb3-b473-46ba-a2f7-3e6e6f6630d5.png)

**Comment by Hasenpfote** [comment]
Draft - 5

正常に動作することを確認済み.  
[`Draft - 4`](https://github.com/Hasenpfote/pyenv_poetry_tox_pytest_example/issues/2#issuecomment-1364930788) をベースに Windows 上での不具合を修正.  

## 機能
- Linux / macOS / Windows で `Poetry` をキャッシュし再利用可能
- `Poetry` が生成する仮想環境をキャッシュし再利用可能
- 各種設定を matrix に移行
- `Poetry` のデフォルトインストールに準拠  
- `Poetry` のバージョンを指定可能
- Windows 上で正しい仮想環境を作成

## YAML

```yaml
name: Draft - 5

on: workflow_dispatch

permissions:
  contents: read

jobs:
  create-cache:
    name: caching 1/2 - ${{ matrix.os }}, ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ['3.7', ]
        poetry_version: ['1.3.1']
        include:
          - os: ubuntu-20.04
            poetry_home: ''
            poetry_path: ''
            poetry_cache_paths: |
              ~/.local/share/pypoetry
              ~/.local/bin/poetry
          - os: macos-latest
            poetry_home: ''
            poetry_path: ${HOME}/.local/bin
            poetry_cache_paths: |
              ~/Library/Application Support/pypoetry
              ~/.local/bin/poetry
          - os: windows-latest
            poetry_home: ''
            #poetry_path: ${APPDATA}\Python\Scripts
            poetry_path: ${APPDATA}\pypoetry\venv\Scripts
            poetry_cache_paths: |
              ~\AppData\Roaming\pypoetry
              ~\AppData\Roaming\Python\Scripts\poetry.exe

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ${{ matrix.poetry_cache_paths }}
          key: temp-0-poetry-${{ matrix.poetry_version }}-${{ matrix.os }}-python-${{ matrix.python-version }}

      - name: Install Poetry for Linux/macOS
        if: runner.os != 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: bash
        env:
          POETRY_VERSION: ${{ matrix.poetry_version }}
          POETRY_HOME: ${{ matrix.poetry_home }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Install Poetry for Windows
        if: runner.os == 'Windows' && steps.cached-poetry.outputs.cache-hit != 'true'
        shell: pwsh
        env:
          POETRY_VERSION: ${{ matrix.poetry_version }}
          POETRY_HOME: ${{ matrix.poetry_home }}
        run: |
          (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -

      - name: Add Poetry to the PATH environment variable
        if: matrix.poetry_path != ''
        shell: bash
        run: |
          echo "${{ matrix.poetry_path }}" >> $GITHUB_PATH
  
      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: temp-0-venv-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Set the environment used by Poetry on Windows 1/2
        if: runner.os == 'Windows' && steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        id: py
        shell: bash
        run: |
          VER='${{ matrix.python-version }}'
          ARR=(${VER//./ })
          echo "tag=${ARR[0]}.${ARR[1]}" >> $GITHUB_OUTPUT

      - name: Set the environment used by Poetry on Windows 2/2
        if: runner.os == 'Windows' && steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        env:
          PY_PYTHON: ${{ steps.py.outputs.tag }}
        run: |
          poetry env use py

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install --no-interaction --no-root --with dev

      - name: Install project
        run: |
          poetry install --no-interaction --only-root

      - name: Test with pytest
        run: |
          poetry run tox -e py
```

## 備考
